{% set name = "pyxDamerauLevenshtein" %}
{% set version = "1.5.3" %}
{% set sha256 = "f88afcc8cb66a05290fb3b159c474a245b05f5061706fd1863ae097ebe55c907" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"
  # Skip Python 3.7+ as the C sources need to be rebuilt from cython for 3.7
  # compatability but are not part of the package.
  skip: true  # [py>36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyxdameraulevenshtein
about:
  home: https://github.com/gfairchild/pyxDamerauLevenshtein
  license: BSD 3-Clause
  summary: 'High performance Damerau-Levenshtein (DL) edit distance
    algorithm for Python.'

  # The remaining entries in this section are optional, but recommended
  description: |
    pyxDamerauLevenshtein implements the Damerau-Levenshtein (DL) edit distance
    algorithm for Python in Cython for high performance.
  doc_url: https://github.com/gfairchild/pyxDamerauLevenshtein
  dev_url: https://github.com/gfairchild/pyxDamerauLevenshtein

extra:
  recipe-maintainers:
    - CJ-Wright
