travis:
  secure:
    BINSTAR_TOKEN: QbTBFf3nhM+77RDZ0L7p+WuVXE/EXpa/yatzDhblSmrRcKS0h4xVdbBMb8MVBP8qOO0CBjnsrldQ4hjV1+7KRgCBpI8grNpZIzWIYhIX0Oh5/iyzk51i3GnBJtk/v4NwogHLe8zXQFzkKJ/OzYDtr6U6K/mRmhm0owQu1z5ma4ezGr8quV2/m01bYpadcP8EgHpkpCZPQSh7z6JkshCuI6H6f8CRtrxrYjiL/+pPNZWtFWMHDrIf8PT/gccSLMpyj3CuAk9KahZx1+9ixgNi8TYLVXz0Q4vnnlPchu6XM9pr17x4KsO8gZnVGWUvs7SjS5yghK8CnJMe7P+dRz1sU2xSpdPQ5eiPIHmnfN9ML4QO1/CLJZvBLsq7Ysc4u7XBWjKPde3Ipo0MvK0lSBPR9fxMoOuXkvXmw7sAcz4Z5HD1M0fKrk956bfrAdmEAKMKckal2NlkmiPuxxvR2Ybm/bp8ueHbh1fv4a1PqrVavdwGeowhhsEFHcmm4XwI9SCj6YJdbjSZF3eBFvn01PPn789BmZXCWxjpfhBnq6U4IB7ZDTcSkjZ6P0ljm9BhCNhykK7X+F+5l7Uvt5jPmm5SxP4cGiUZG11JFiCMjjN193LjICynQkGk5c2+Y6XGF1WqY6Kjf9LP1wqwEG/EkHxy57xMNme0QPpsR1INAxlLpFU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
