travis:
  secure:
    BINSTAR_TOKEN: Wkc0fAbZQwWg5BN41KG9DL2lO/F79KTqIv3qurG61O6yAgvwuJa675LiQRxy9v1E6j3L/E4mjuyS3ynmFbRUZZO2SP8mucQf38Jl+ADGMd4lFLwD/U/I6UmFsjva15cNo7smetm/yLGQxjxucool2smxsVlvI/rQo6sqJP6HesrJ1y4EtPmEtXmhKmug+D7xjDlrEC9Wo3xmMh58C213VlD5YZefP5wMdRaMfNeQI97I6HZsk8y7RyrQ4YdYwEOJhzVyISLlSVV1blo44lrjZEQd7a+570InpbSA17xlrYzs8MVv2nDz1y014jy+NoNBTcn7VV+5r5oV5JXUpfcxNox/AaPFxl5IQUIw+yCyWoXHCj5Yk9MPEDghRo7Vfm1OGz1UIB5g0Q3Sc/mmAgMfG8WTUsV0Knvd1XnH7fBXe4DV6qAb2uejAwg9H+KAmHXtHY0vJBLhWTn+5s8WxJVVcnoIkKsHAcKg9v99ZqfgMo8zNPXYYCWGdKuCxBoYanz9KPSvXDyMFwnpUxdjYY8I1aqiN0u29xz2rBRKVjsc+7sy16ewC4t6iCcu6PYpxe8S9w5m7437WZy2Q3sOemKTuC2kNfuhZ2YDLyA0GTzUQ4VPi+yyGy8JLHw8e0d54kW+AH/8KejBrQGYS05/Yqn8oMHOA4gaTBzcZw6O7IAa+rs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
